# Generated by Django 4.1.7 on 2023-03-05 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comp', models.CharField(choices=[('21 a 20', '21 a 20'), ('01 a 30', '01 a 30')], max_length=50, verbose_name='Tipo de Competência')),
                ('mes', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=50, verbose_name='Mês')),
                ('ano', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=50, verbose_name='Ano')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=54, verbose_name='RG')),
                ('cpf', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='CPF')),
                ('pis', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='PIS')),
            ],
        ),
        migrations.CreateModel(
            name='RegraDePonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da Regra de Ponto')),
                ('toleranciaentrada', models.DurationField()),
                ('toleranciasaida', models.DurationField()),
                ('horaextraautorizada', models.BooleanField(default=False)),
                ('periodohoranoturna_inicio', models.TimeField()),
                ('periodohoranoturna_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('entrada_almoco', models.TimeField(blank=True, null=True)),
                ('saida_almoco', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.competencia')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status Ativo/Inativo')),
                ('matricula', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Matricula')),
                ('centraodecusto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.centrodecusto')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.departamento')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.filial')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.funcionario')),
                ('regradeponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_eletronico.regradeponto')),
            ],
        ),
    ]
