# Generated by Django 4.1.7 on 2023-03-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_eletronico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
    ]
