# Generated by Django 4.1.7 on 2023-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_eletronico', '0002_competencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='nome',
        ),
        migrations.AddField(
            model_name='competencia',
            name='ano',
            field=models.IntegerField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencia',
            name='mes',
            field=models.IntegerField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], default=1),
            preserve_default=False,
        ),
    ]
