# Generated by Django 4.1.7 on 2023-03-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_eletronico', '0003_remove_competencia_nome_competencia_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='ano',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=50, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='mes',
            field=models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=50, verbose_name='Mês'),
        ),
    ]
