# Generated by Django 4.1.7 on 2023-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_eletronico', '0004_alter_competencia_ano_alter_competencia_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='tipo_comp',
            field=models.CharField(choices=[('21 a 20', '21 a 20'), ('01 a 30', '01 a 30')], default=1, max_length=50, verbose_name='Tipo de Competência'),
            preserve_default=False,
        ),
    ]
